#!/bin/bash
#
# Copyright (c) 2019 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0
#

set -e

scripts=$(dirname $0)

echo "Setting up glide"
go get -v github.com/Masterminds/glide

echo "Running glide up with strip vendor flag"
glide up --strip-vendor
